# Enlaces de utilidad

-   [Angiosperm Phylogeny Website](http://www.mobot.org/MOBOT/Research/APweb/welcome.html)

-   [Árboles del Alma](https://www.udea.edu.co/wps/portal/udea/web/inicio/unidades-academicas/ciencias-exactas-naturales/herbario/Contenido/asContenidosMenu/contPreguntasFrecuentes/arboles-alma)

-   [Arboretum y Palmetum "León morales Soto"](https://experience.arcgis.com/experience/2c21aad3fb5944f58b461377a5736238)

-   [Atlas de histología vegetal y animal](https://mmegias.webs.uvigo.es)

-   [Biología de Plantas de Miguel Ángel Gamboa Gaitan](http://red.unal.edu.co/cursos/ciencias/2015877/index.html)

-   [Catálogo de árboles urbanos en Colombia](https://catalogoarbolesurbanos.eia.edu.co)

-   [Catálogo de las Plantas Vasculares del Departamento de Antioquia, Colombia](http://legacy.tropicos.org/Project/Catalogo-de-Antioquia)

<!-- -   [Catálogo de plantas y líquenes de Colombia](http://catalogoplantasdecolombia.unal.edu.co) -->

-   [Catálogo ilustrado de la flora de los páramos del Departamento de Antioquia, Colombia](http://legacy.tropicos.org/Project/Catalogo-de-Antioquia)

-   [Catálogo virtual de flora del Valle de Aburrá](https://catalogofloravalleaburra.eia.edu.co)

-   [Colecciones científicas en línea del ICN](http://www.biovirtual.unal.edu.co/es/)

<!-- -   [Curso de Botánica FAGRO](http://www.fagro.edu.uy/~bioveg/botanica.html) -->

-   [Glossary for Vascular Plants](https://sweetgum.nybg.org/science/glossary/)

-   [Herbario Universidad de Antioquia (HUA)](https://www.udea.edu.co/wps/portal/udea/web/inicio/unidades-academicas/ciencias-exactas-naturales/herbario)

-   [Hipertextos de Morfología de Plantas Vasculares: Botánica Morfológica](http://www.biologia.edu.ar/botanica/)

-   [Inventario forestal de la Universidad de Antioquia](https://www.udea.edu.co/wps/portal/udea/web/generales/interna/asInstitucional/UdeA+Sostenible/asContenidos/asListado/mapas-arboles-medellin)

<!-- -   [Laboratorio de Sistemática de Plantas Vasculares](https://www.thecompositaehut.com/www_tch/webcurso_spv/familias_pv.html) -->

-   [Mapeando los yarumos de Medellín](https://alexespinosaco.github.io/cecropia-medellin/)

-   [Nombres comunes de las plantas de Colombia](http://www.biovirtual.unal.edu.co/nombrescomunes/es/)

-   [Oxford Plants 400](https://herbaria.plants.ox.ac.uk/bol/plants400)

-   [Plantas y Hongos](https://www.plantasyhongos.es/index.htm)

-   [Plants of the World Online (POWO)](https://powo.science.kew.org)

-   [Sistema de Árbol Urbano de Medellín y el Área Metropolitana del Valle de Áburra](https://www.medellin.gov.co/sau)

-   [The Open Science Laboratory - A-Level Virtual microscopy](https://learn5.open.ac.uk/course/format/sciencelab/section.php?name=avm_open)

-   [Tropicos](https://tropicos.org/home)

-   [Useful Plants of Colombia (ColPlanta)](https://www.colplanta.org)

-   [World Flora Online](https://www.worldfloraonline.org)

