---
title: "Biología de las Plantas (2026-2)"
# subtitle: "Instituto de Biología, Universidad de Antioquia"
description: |
  Sitio web del curso Biología de las Plantas (2026-2) del Instituto de Biología de la Universidad de Antioquia

author: 
  - name: "Álex Espinosa-Correa"
    email: alex.espinosa@udea.edu.co
    url: https://alexespinosaco.github.io/
    orcid: 0000-0002-7353-1182
    affiliation: "Grupo de Estudios Botánicos GEOBOTA, Instituto de Biología, Facultad de Ciencias Exactas y Naturales, Universidad de Antioquia UdeA, Calle 70 No. 52-21, Medellín, Colombia"
    affiliation-url: https://geobota.github.io/

date: 2026-08-03
date-modified: today

citation: true
engine: knitr
---

```{r}
#| label: setup
#| echo: false
#| message: false
#| warning: false

library("here")

base::source(
  here::here(
    "scripts",
    "script_cronograma_evaluacion.R"
  )
)
```

::::: {.panel-tabset}

## Oriente

### Cronograma

::: {.light-content}
```{r}
#| label: cronograma-oriente-light
#| echo: false
#| message: false
#| html-table-processing: none

tbl_cronograma_oriente |> 
  gt::tab_options(
    table.background.color = "#fff",
    table.font.color = "#212529"
  )
```
:::

::: {.dark-content}
```{r}
#| label: cronograma-oriente-dark
#| echo: false
#| message: false
#| html-table-processing: none

tbl_cronograma_oriente |> 
  gt::tab_options(
    table.background.color = "#222",
    table.font.color = "#dee2e6"
  )
```
:::

### Evaluación general

::: {.light-content}
```{r}
#| label: evaluacion-oriente-general-light
#| echo: false
#| message: false
#| html-table-processing: none

tbl_evaluacion_general |> 
  gt::tab_options(
    table.background.color = "#fff",
    table.font.color = "#212529"
  )
```
:::

::: {.dark-content}
```{r}
#| label: evaluacion-oriente-general-dark
#| echo: false
#| message: false
#| html-table-processing: none

tbl_evaluacion_general |> 
  gt::tab_options(
    table.background.color = "#222",
    table.font.color = "#dee2e6"
  )
```
:::

### Evaluación laboratorio

::: {.light-content}
```{r}
#| label: evaluacion-oriente-laboratorio-light
#| echo: false
#| message: false
#| html-table-processing: none

tbl_evaluacion_laboratorio |> 
  gt::tab_options(
    table.background.color = "#fff",
    table.font.color = "#212529"
  )
```
:::

::: {.dark-content}
```{r}
#| label: evaluacion-oriente-laboratorio-dark
#| echo: false
#| message: false
#| html-table-processing: none

tbl_evaluacion_laboratorio |> 
  gt::tab_options(
    table.background.color = "#222",
    table.font.color = "#dee2e6"
  )
```
:::

## Urabá

### Cronograma

::: {.light-content}
```{r}
#| label: cronograma-uraba-light
#| echo: false
#| message: false
#| html-table-processing: none

tbl_cronograma_uraba |> 
  gt::tab_options(
    table.background.color = "#fff",
    table.font.color = "#212529"
  )
```
:::

::: {.dark-content}
```{r}
#| label: cronograma-uraba-dark
#| echo: false
#| message: false
#| html-table-processing: none

tbl_cronograma_uraba |> 
  gt::tab_options(
    table.background.color = "#222",
    table.font.color = "#dee2e6"
  )
```
:::

### Evaluación general

::: {.light-content}
```{r}
#| label: evaluacion-uraba-general-light
#| echo: false
#| message: false
#| html-table-processing: none

tbl_evaluacion_general |> 
  gt::tab_options(
    table.background.color = "#fff",
    table.font.color = "#212529"
  )
```
:::

::: {.dark-content}
```{r}
#| label: evaluacion-uraba-general-dark
#| echo: false
#| message: false
#| html-table-processing: none

tbl_evaluacion_general |> 
  gt::tab_options(
    table.background.color = "#222",
    table.font.color = "#dee2e6"
  )
```
:::

:::::
